FROM nginx:stable-alpine

ARG VERSION=1.3.7 GHPROXY=https://gh.wglee.org/

ENV RPC_SECRET=aria2@123456 \
    DOWNLOAD_DIR=/downloads

COPY install.sh /
COPY run-aria2.sh /docker-entrypoint.d/

RUN  sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
     apk add --no-cache aria2 curl bash && \
     /bin/bash /install.sh && \
     curl -sL ${GHPROXY}https://github.com/mayswind/AriaNg/releases/download/${VERSION}/AriaNg-${VERSION}-AllInOne.zip -o /tmp/AriaNg.zip && \
     unzip -o  /tmp/AriaNg.zip -d /usr/share/nginx/html && /bin/rm -f /tmp/AriaNg.zip

EXPOSE 80 6800

