---
version: '3.1'

services:
  ubuntu:
    image: liwanggui/ubuntu-desktop-novnc
    container_name: ubuntu
    restart: always
    environment:
      - VNCPASSWD=admin123      # 默认 admin123456
      - ROOT_PASSWORD=root@123  # 默认 root
    ports:
      - 2222:22
      - 6080:6080
      - 5900:5900
    volumes:
      - ./data:/root
